# Generated by Django 3.1.7 on 2021-02-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210223_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categorys',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
